services:
  caddy:
    image: caddy:latest
    container_name: adl-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ".env"
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - adl-network
  mongodb:
    image: ghcr.io/adl-lex/adl-mongodb:latest
    container_name: adl-mongodb
    env_file:
      - ".env"
    ports:
      - "27017:27017"
    networks:
      - adl-network
  mongo-import:
    image: ghcr.io/adl-lex/adl-mongodb:latest
    container_name: adl-mongo-import
    env_file:
      - ".env"
    volumes:
      - ./data:/data
    networks:
      - adl-network
    depends_on:
      - mongodb
    command:
      - bash
      - -c
      - |
        sleep 10
        mongoimport \
          -u $$MONGO_INITDB_ROOT_USERNAME \
          -p $$MONGO_INITDB_ROOT_PASSWORD \
          --authenticationDatabase admin \
          --host mongodb:27017 \
          --db wb \
          --collection bwb \
          --jsonArray \
          --file /data/input.json
    restart: "no"
networks:
  adl-network:
    driver: bridge
volumes:
  caddy_data:
  caddy_config: