services:
  caddy:
    image: caddy:latest
    container_name: adl-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ".env"
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - adl-network
  mongodb:
    image: ghcr.io/adl-lex/adl-mongodb:latest
    container_name: adl-mongodb
    env_file:
      - ".env"
    ports:
      - "27017:27017"
    networks:
      - adl-network
    restart: unless-stopped
  mongo-import:
    image: ghcr.io/adl-lex/adl-mongodb:latest
    container_name: adl-mongo-import
    env_file:
      - ".env"
    volumes:
      - ./data:/data
    networks:
      - adl-network
    depends_on:
      - mongodb
    command:
      - bash
      - -c
      - |
        until mongosh --host mongodb:27017 --eval "quit(db.runCommand('ping').ok ? 0 : 2)" --quiet; do
          echo "Waiting for MongoDB..."
          sleep 2
        done
        echo "MongoDB is ready, starting import..."
        mongoimport \
          -u $$MONGO_INITDB_ROOT_USERNAME \
          -p $$MONGO_INITDB_ROOT_PASSWORD \
          --authenticationDatabase admin \
          --host mongodb:27017 \
          --db wb \
          --collection bwb \
          --jsonArray \
          --file /data/input.json
    restart: "no"
  adl-api:
    image: ghcr.io/adl-lex/adl-api:latest
    container_name: adl-api
    env_file:
      - ".env"
    ports:
      - "5000:80"
    networks:
      - adl-network
    depends_on:
      - mongodb
    restart: unless-stopped
    command:
      [
        "uv",
        "run",
        "fastapi",
        "run",
        "app/main.py",
        "--proxy-headers",
        "--port",
        "80",
        "--root-path",
        "/api",
      ]
  adl-platform:
    image: ghcr.io/adl-lex/adl-platform:latest
    container_name: adl-platform
    env_file:
      - ".env"
    ports:
      - "3000:3000"
    networks:
      - adl-network
    depends_on:
      - adl-api
    restart: unless-stopped
networks:
  adl-network:
    driver: bridge
volumes:
  caddy_data:
  caddy_config:
