services:
  caddy:
    image: caddy:latest
    container_name: adl-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ".env"
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
      - /wb/static:/wb/static:ro
    networks:
      - adl-network
  mongodb:
    image: ghcr.io/pdl-lex/pdl-mongodb:latest
    container_name: adl-mongodb
    env_file:
      - ".env"
    ports:
      - "27017:27017"
    networks:
      - adl-network
    restart: unless-stopped
  adl-api:
    image: ghcr.io/pdl-lex/pdl-api:latest
    container_name: adl-api
    env_file:
      - ".env"
    ports:
      - "5000:80"
    networks:
      - adl-network
    depends_on:
      - mongodb
    restart: unless-stopped
    command:
      [
        "uv",
        "run",
        "fastapi",
        "run",
        "app/main.py",
        "--proxy-headers",
        "--port",
        "80",
      ]
  adl-platform:
    image: ghcr.io/pdl-lex/pdl-platform:latest
    container_name: adl-platform
    env_file:
      - ".env"
    ports:
      - "3000:3000"
    networks:
      - adl-network
    depends_on:
      - adl-api
    restart: unless-stopped
  pdl-api-postgres:
    build: ./postgres-api
    container_name: pdl-api-postgres
    env_file:
      - ".env"
    ports:
      - "8001:80"
    networks:
      - adl-network
    restart: unless-stopped
    command:
      [
        "uv",
        "run",
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
        "--proxy-headers",
      ]
  postgres:
    image: postgres:18-alpine
    container_name: pdl-db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - /mnt/data/wb/data:/var/lib/postgresql/data
      - /mnt/data/wb/import:/import
    networks:
      - adl-network
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: wb_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      SCRIPT_NAME: /pgadmin
    networks:
      - adl-network
networks:
  adl-network:
    driver: bridge
volumes:
  caddy_data:
  caddy_config:
